# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=20)),
                ('semester', models.CharField(default='', max_length=4)),
                ('code', models.CharField(default='', max_length=20, unique=True)),
                ('credits', models.FloatField(default=0)),
                ('title', models.CharField(default='', max_length=40)),
                ('professor', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=20)),
                ('obligatory', models.BooleanField(default=True)),
                ('note', models.CharField(default='', max_length=50)),
                ('discipline', models.CharField(default='', max_length=20)),
                ('category', models.CharField(default='', max_length=3)),
            ],
        ),
    ]
